import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'
import Image from 'next/image'

import logo from '../../public/images/Logo.png';
import SideBar from './components/SideBar/SideBar';
import Footer from './components/Footer/Footer';
import Header from './components/Header/Header';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'DashBord',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
      </head>
      <body className={inter.className}>


        <div className="drawer lg:drawer-open">
          <input id="my-drawer-2" type="checkbox" className="drawer-toggle" />
          <div className="drawer-content">
            {/* Page content here */}
            <Header></Header>
            {children}
            <Footer></Footer>
          </div>
          
          <div className="drawer-side">
            <label htmlFor="my-drawer-2" className="drawer-overlay"></label>
            <ul className="menu p-4 w-80 h-full bg-white text-base-content">
              {/* Sidebar content here */}

              <div className='mb-[60px]'>
                <Link href='' className="btn btn-ghost normal-case text-xl ">
                  <Image src={logo} alt='logo' />
                  DashPro
                </Link>
              </div>


              <SideBar></SideBar>

            </ul>

          </div>
        </div>
      </body>
    </html>
  )
}
